import 'package:flutter/material.dart';
import '../../core/theme/app_colors.dart';
import 'tutorial_step.dart';
import 'tutorial_keys.dart';

final List<TutorialStep> tutorialSteps = [
  // 🚀 PHASE 0 — BIENVENUE
  TutorialStep(
    id: 'welcome',
    title: 'BIENVENUE DANS FORGERON',
    description: 'Votre poste de commande CNC 5-axes industriel haute performance. Prêt à dompter la matière avec une précision extrême ?',
    page: 'dashboard',
    spotlightShape: SpotlightShape.none,
    tooltipPosition: TooltipPosition.center,
    icon: Icons.rocket_launch,
    accentColor: AppColors.primary,
    action: 'COMMENCER LA VISITE GUIDÉE ›',
  ),

  // 🔌 PHASE 1 — CONNEXION
  TutorialStep(
    id: 'header',
    title: 'BARRE DE TITRE INTELLIGENTE',
    description: 'Surveillez en un coup d\'œil l\'état de connexion et le statut temps-réel de votre machine FluidNC.',
    targetKey: TutorialKeys.headerBar,
    page: 'dashboard',
    icon: Icons.info_outline,
    accentColor: AppColors.primary,
  ),
  TutorialStep(
    id: 'estop',
    title: 'ARRÊT D\'URGENCE LOGICIEL',
    description: 'En cas de problème, ce bouton envoie immédiatement une commande de Soft Reset à l\'ESP32 pour figer tout mouvement.',
    targetKey: TutorialKeys.emergencyStopBtn,
    page: 'dashboard',
    icon: Icons.warning_amber,
    accentColor: AppColors.danger,
  ),
  TutorialStep(
    id: 'network_settings',
    title: 'PARAMÈTRES RÉSEAU',
    description: 'Accédez à la configuration IP de l\'ESP32, scannez le réseau, ou changez le port.',
    targetKey: TutorialKeys.settingsBtn,
    page: 'dashboard',
    icon: Icons.settings_ethernet,
    accentColor: AppColors.secondary,
  ),

  // 🗺️ PHASE 2 — NAVIGATION
  TutorialStep(
    id: 'sidebar',
    title: 'NAVIGATION LATÉRALE',
    description: 'Accédez instantanément aux 6 modules métiers : Dashboard, Palpage, Outils, Fichiers, MDI et Diagnostics.',
    targetKey: TutorialKeys.sidebar,
    page: 'dashboard',
    tooltipPosition: TooltipPosition.right,
    icon: Icons.menu_open,
    accentColor: AppColors.primary,
  ),
  TutorialStep(
    id: 'menu_toggle',
    title: 'REPLIER LE MENU',
    description: 'Gagnez de l\'espace de travail précieux en réduisant la barre latérale aux icônes seules.',
    targetKey: TutorialKeys.menuToggleBtn,
    page: 'dashboard',
    icon: Icons.menu,
    accentColor: AppColors.textSecondary,
  ),
  TutorialStep(
    id: 'footer',
    title: 'TÉLÉMÉTRIE TEMPS RÉEL',
    description: 'Coordonnées X/Y/Z/A/C, vitesses d\'avance (F) et de broche (S) mises à jour toutes les 100ms.',
    targetKey: TutorialKeys.statusFooter,
    page: 'dashboard',
    tooltipPosition: TooltipPosition.top,
    icon: Icons.speed,
    accentColor: AppColors.success,
  ),

  // 📊 PHASE 3 — DASHBOARD
  TutorialStep(
    id: 'dashboard_overview',
    title: 'TABLEAU DE BORD PRINCIPAL',
    description: 'Le cockpit central de votre machine. Tout est pensé pour l\'efficacité opérationnelle en atelier.',
    page: 'dashboard',
    spotlightShape: SpotlightShape.none,
    tooltipPosition: TooltipPosition.center,
    icon: Icons.dashboard,
    accentColor: AppColors.primary,
  ),
  TutorialStep(
    id: 'dro',
    title: 'DRO (DIGITAL READ-OUT)',
    description: 'Visualisation ultra-claire des positions machine. Basculez entre coordonnées Machines (MPos) et Pièces (WPos) d\'un clic.',
    targetKey: TutorialKeys.droPanel,
    page: 'dashboard',
    tooltipPosition: TooltipPosition.left,
    icon: Icons.grid_3x3,
    accentColor: AppColors.secondary,
  ),
  TutorialStep(
    id: 'action_btns',
    title: 'COMMANDES D\'ACTION',
    description: 'Lancement du cycle, mise en pause, arrêt d\'urgence, ou retour à l\'origine rapide.',
    targetKey: TutorialKeys.actionButtons,
    page: 'dashboard',
    icon: Icons.play_circle_outline,
    accentColor: AppColors.success,
  ),
  TutorialStep(
    id: 'overrides',
    title: 'OVERRIDES DE VITESSE',
    description: 'Ajustez en temps réel la vitesse d\'avance (F%) et la broche (S%) sans modifier votre programme.',
    targetKey: TutorialKeys.overridesPanel,
    page: 'dashboard',
    tooltipPosition: TooltipPosition.right,
    icon: Icons.tune,
    accentColor: AppColors.info,
  ),
  TutorialStep(
    id: 'macros',
    title: 'MACROS INDUSTRIELLES',
    description: 'Exécutez vos séquences complexes (changement d\'outil, nettoyage) enregistrées sous forme de scripts G-Code.',
    targetKey: TutorialKeys.macrosPanel,
    page: 'dashboard',
    tooltipPosition: TooltipPosition.left,
    icon: Icons.code,
    accentColor: AppColors.warning,
  ),
  TutorialStep(
    id: 'visualizer',
    title: 'JUMEAU NUMÉRIQUE 3D',
    description: 'Visualisez les mouvements de la cinématique Trunnion en temps réel.',
    targetKey: TutorialKeys.trunnionViz,
    page: 'dashboard',
    tooltipPosition: TooltipPosition.bottom,
    icon: Icons.view_in_ar,
    accentColor: AppColors.primary,
  ),
  TutorialStep(
    id: 'gcode_console',
    title: 'CONSOLE DE FLUX G-CODE',
    description: 'Aperçu du programme chargé avec la ligne courante surlignée. Virtualisation pour les fichiers massifs (>1M lignes).',
    targetKey: TutorialKeys.gcodeConsole,
    page: 'dashboard',
    tooltipPosition: TooltipPosition.top,
    icon: Icons.terminal,
    accentColor: AppColors.axisZ,
  ),
  TutorialStep(
    id: 'status_cockpit',
    title: 'COCKPIT DE STATUT',
    description: 'Badge de statut avec couleur et pulsation, progression, et informations sur le travail en cours.',
    targetKey: TutorialKeys.statusCockpit,
    page: 'dashboard',
    tooltipPosition: TooltipPosition.top,
    icon: Icons.donut_large,
    accentColor: AppColors.success,
  ),

  // 🎯 PHASE 4 — PALPAGE
  TutorialStep(
    id: 'probing_overview',
    title: 'PALPAGE & ORIGINES',
    description: 'Définissez vos systèmes de coordonnées (G54-G59) et gérez vos prises d\'origines avec précision.',
    page: 'probing',
    spotlightShape: SpotlightShape.none,
    tooltipPosition: TooltipPosition.center,
    icon: Icons.center_focus_strong,
    accentColor: AppColors.secondary,
  ),
  TutorialStep(
    id: 'wcs_cards',
    title: 'GESTION DES WCS',
    description: 'Sélectionnez un système de coordonnées pièce, cliquer envoie G54/G55/G56 à la machine.',
    targetKey: TutorialKeys.wcsCards,
    page: 'probing',
    icon: Icons.layers,
    accentColor: AppColors.info,
  ),
  TutorialStep(
    id: 'jog_panel',
    title: 'PAVÉ DE JOGGING 5-AXES',
    description: 'Déplacez manuellement les axes linéaires et rotatifs avec des pas ultra-précis.',
    targetKey: TutorialKeys.jogPanel,
    page: 'probing',
    tooltipPosition: TooltipPosition.left,
    icon: Icons.open_with,
    accentColor: AppColors.primary,
  ),
  TutorialStep(
    id: 'probing_tools',
    title: 'BOUTONS DE PALPAGE',
    description: 'Routines automatiques de palpage surface, centrage avec résultat [PRB:] retourné.',
    targetKey: TutorialKeys.probingTools,
    page: 'probing',
    icon: Icons.straighten,
    accentColor: AppColors.warning,
  ),
  TutorialStep(
    id: 'probing_offsets',
    title: 'OFFSETS ET ORIGINES',
    description: 'Utilise G10 L20 pour définir l\'origine pièce à la position courante en un clic.',
    targetKey: TutorialKeys.probingOffsets,
    page: 'probing',
    icon: Icons.my_location,
    accentColor: AppColors.success,
  ),

  // 🔧 PHASE 5 — MAGASIN D'OUTILS
  TutorialStep(
    id: 'tool_overview',
    title: 'MAGASIN D\'OUTILS',
    description: 'Gérez la jauge de vos outils, leur longueur, diamètre et matière.',
    page: 'tools',
    spotlightShape: SpotlightShape.none,
    tooltipPosition: TooltipPosition.center,
    icon: Icons.build,
    accentColor: AppColors.primary,
  ),
  TutorialStep(
    id: 'tool_table',
    title: 'TABLEAU D\'OUTILS',
    description: 'Sélectionnez un outil (T1-T99) pour appliquer automatiquement la compensation de longueur (G43).',
    targetKey: TutorialKeys.toolTable,
    page: 'tools',
    icon: Icons.list_alt,
    accentColor: AppColors.info,
  ),
  TutorialStep(
    id: 'calibration_wizard',
    title: 'WIZARD DE CALIBRATION',
    description: 'Procédure guidée de mesure de longueur d\'outil via palpeur automatisé.',
    targetKey: TutorialKeys.calibrationWizard,
    page: 'tools',
    icon: Icons.auto_fix_high,
    accentColor: AppColors.secondary,
  ),

  // 📁 PHASE 6 — ESPACE DE TRAVAIL
  TutorialStep(
    id: 'file_manager_overview',
    title: 'GESTIONNAIRE DE FICHIERS',
    description: 'Chargez des programmes G-Code locaux (.nc, .gcode, .tap).',
    targetKey: TutorialKeys.fileManager,
    page: 'files',
    icon: Icons.folder_open,
    accentColor: AppColors.primary,
  ),
  TutorialStep(
    id: 'gcode_preview',
    title: 'PRÉVISUALISATION',
    description: 'Aperçu du contenu du fichier, nombre de lignes, analyse des coordonnées min/max.',
    targetKey: TutorialKeys.gcodePreview,
    page: 'files',
    icon: Icons.preview,
    accentColor: AppColors.info,
  ),
  TutorialStep(
    id: 'stream_btn',
    title: 'ENVOI OPTIMISÉ',
    description: 'Lancement de l\'usinage avec notre algorithme de Character-Counting pour un streaming fluide sans saccades.',
    targetKey: TutorialKeys.streamBtn,
    page: 'files',
    icon: Icons.send,
    accentColor: AppColors.success,
  ),

  // ⌨️ PHASE 7 — TERMINAL MDI
  TutorialStep(
    id: 'mdi_overview',
    title: 'TERMINAL MDI',
    description: 'Entrée manuelle de commandes G-Code ligne par ligne avec coloration syntaxique.',
    targetKey: TutorialKeys.mdiInput,
    page: 'mdi',
    icon: Icons.terminal,
    accentColor: AppColors.primary,
  ),
  TutorialStep(
    id: 'mdi_history',
    title: 'HISTORIQUE & RÉPONSES',
    description: 'Consultez toutes les réponses FluidNC (ok, error, [MSG:]) en temps réel.',
    targetKey: TutorialKeys.mdiHistory,
    page: 'mdi',
    icon: Icons.history,
    accentColor: AppColors.secondary,
  ),

  // 🩺 PHASE 8 — DIAGNOSTICS
  TutorialStep(
    id: 'network_monitor',
    title: 'MONITEUR RÉSEAU',
    description: 'Flux temps réel de tout le trafic WebSocket (TX/RX) pour le débogage.',
    targetKey: TutorialKeys.networkMonitor,
    page: 'diagnostics',
    icon: Icons.network_check,
    accentColor: AppColors.info,
  ),
  TutorialStep(
    id: 'performance_metrics',
    title: 'MÉTRIQUES DE PERFORMANCE',
    description: 'Surveillance de la latence, du débit, et de l\'état du buffer GRBL.',
    targetKey: TutorialKeys.performanceMetrics,
    page: 'diagnostics',
    icon: Icons.insights,
    accentColor: AppColors.warning,
  ),

  // 🔌 PHASE 9 — CONNEXION
  TutorialStep(
    id: 'network_config',
    title: 'CONFIGURATION RÉSEAU',
    description: 'Entrez l\'IP de l\'ESP32 (ex: 192.168.137.200) et le port WebSocket.',
    targetKey: TutorialKeys.networkConfig,
    page: 'settings',
    icon: Icons.wifi,
    accentColor: AppColors.primary,
  ),
  TutorialStep(
    id: 'scanner_btn',
    title: 'SCANNER INTELLIGENT',
    description: 'L\'application scanne le sous-réseau pour détecter automatiquement la carte FluidNC.',
    targetKey: TutorialKeys.scannerBtn,
    page: 'settings',
    icon: Icons.radar,
    accentColor: AppColors.success,
  ),

  // 🎉 PHASE 10 — FIN
  TutorialStep(
    id: 'end',
    title: 'VOUS ÊTES PRÊT À FORGER !',
    description: 'Le tour d\'horizon est terminé. Vous avez maintenant toutes les clés pour piloter votre CNC avec Forgeron.',
    page: 'dashboard',
    spotlightShape: SpotlightShape.none,
    tooltipPosition: TooltipPosition.center,
    icon: Icons.check_circle_outline,
    accentColor: AppColors.success,
    action: 'COMMENCER À USINER',
  ),
];
